set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

# YooBox Y1 uses RK3562; build the application with the ROCKNIX RK3566 SDK.
set(TOOLCHAIN_DIR "$ENV{HOME}/distribution/build.ROCKNIX-RK3566.aarch64/toolchain"
    CACHE PATH "ROCKNIX RK3566 aarch64 toolchain directory")
set(ROCKNIX_TARGET_TRIPLE "aarch64-rocknix-linux-gnu"
    CACHE STRING "Compiler prefix and sysroot directory name in the ROCKNIX SDK")
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES TOOLCHAIN_DIR ROCKNIX_TARGET_TRIPLE)
set(CROSS_PREFIX "${TOOLCHAIN_DIR}/bin/${ROCKNIX_TARGET_TRIPLE}")
set(SYSROOT "${TOOLCHAIN_DIR}/${ROCKNIX_TARGET_TRIPLE}/sysroot")

set(CMAKE_C_COMPILER ${CROSS_PREFIX}-gcc)
set(CMAKE_CXX_COMPILER ${CROSS_PREFIX}-g++)
set(CMAKE_AR ${CROSS_PREFIX}-gcc-ar)
set(CMAKE_RANLIB ${CROSS_PREFIX}-gcc-ranlib)
set(CMAKE_STRIP ${CROSS_PREFIX}-strip)

set(CMAKE_SYSROOT ${SYSROOT})

set(CMAKE_FIND_ROOT_PATH ${SYSROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_C_FLAGS_INIT "-march=armv8-a -mtune=cortex-a53")
set(CMAKE_CXX_FLAGS_INIT "-march=armv8-a -mtune=cortex-a53")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-L${SYSROOT}/usr/lib -Wl,-rpath,/usr/lib -Wl,-rpath-link,${SYSROOT}/usr/lib")
