set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(TOOLCHAIN_DIR /home/ice/distribution/build.ROCKNIX-RK3326.aarch64/toolchain)
set(CROSS_PREFIX ${TOOLCHAIN_DIR}/bin/aarch64-rocknix-linux-gnueabi)
set(SYSROOT ${TOOLCHAIN_DIR}/aarch64-rocknix-linux-gnueabi/sysroot)

set(CMAKE_C_COMPILER ${CROSS_PREFIX}-gcc)
set(CMAKE_CXX_COMPILER ${CROSS_PREFIX}-g++)
set(CMAKE_AR ${CROSS_PREFIX}-gcc-ar)
set(CMAKE_RANLIB ${CROSS_PREFIX}-gcc-ranlib)
set(CMAKE_STRIP ${CROSS_PREFIX}-strip)

set(CMAKE_SYSROOT ${SYSROOT})

set(CMAKE_FIND_ROOT_PATH ${SYSROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_C_FLAGS_INIT "-I${SYSROOT}/usr/include")
set(CMAKE_CXX_FLAGS_INIT "-I${SYSROOT}/usr/include")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-L${SYSROOT}/usr/lib -Wl,-rpath,/usr/lib")
